spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    producer:
      retries: 10
    consumer:
      properties:
        reconnect:
          backoff:
            ms: 1000
            max.ms: 10000